version: "3"
services:
  firefox:
    image: selenium/standalone-firefox-debug:3.141.59-20210311
    environment:
      SCREEN_WIDTH: 1440
      SCREEN_HEIGHT: 900
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"